### ISSUE TITLE
trace and auto decompile

### ISSUE THREAD

**Issue by ssst0n3** [ssst0n3/opdb#1]

**Comment by ssst0n3** [comment]
```
main
main
[INFO] [disassemble_string] 0 LOAD_GLOBAL 0(f)
Traceback (most recent call last):
  File "trace.py", line 87, in <module>
    main()
  File "trace.py", line 83, in main
    run(filename)
  File "trace.py", line 78, in run
    exec(code_object, globals(), locals())
  File "sample.py", line 13, in <module>
  File "sample.py", line 8, in main
NameError: global name 'f' is not defined
```

**Comment by ssst0n3** [comment]
done
